/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tictac;

import javax.swing.JButton;

/**
 *
 * @author dell
 */
public class Board2 extends javax.swing.JFrame {

    /**
     * Creates new form Board2
     */
    Btn btnArr[][]=new Btn[3][3];
    PlayCom pyr=new PlayCom();
    public Board2() {
        initComponents();
        for(int i=0;i<3;i++)
        {
            for (int j = 0; j <3; j++) 
            {
                btnArr[i][j]=new Btn();
            }
            
        }
        btnArr[0][0].btn=jButton1;
        btnArr[0][1].btn=jButton2;
        btnArr[0][2].btn=jButton3;
        btnArr[1][0].btn=jButton4;
        btnArr[1][1].btn=jButton5;
        btnArr[1][2].btn=jButton6;
        btnArr[2][0].btn=jButton7;
        btnArr[2][1].btn=jButton8;
        btnArr[2][2].btn=jButton9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("jButton9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("jButton10");

        jButton11.setText("jButton11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7)
                            .addComponent(jButton4)
                            .addComponent(jButton1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton9)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(jButton10)
                                .addGap(67, 67, 67))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(55, 55, 55)
                .addComponent(jButton11)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int row,clm,rowVal,clmVal;
    int row1[]=new int[3],clm1[]=new int[3];
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(pyr.val==1)
        {
            btnArr[0][0].status=true;
            btnArr[0][0].btn.setText("X");
            btnArr[0][0].value=1;
            
            row=checkRow();
            clm=checkClm();
            putSign();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            btnArr[0][1].status=true;
            btnArr[0][1].btn.setText("X");
            btnArr[0][1].value=1;
            row=checkRow();
            clm=checkClm();
            putSign();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            btnArr[0][2].status=true;
            btnArr[0][2].btn.setText("X");
            btnArr[0][2].value=1;
            row=checkRow();
            clm=checkClm();
            putSign();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            btnArr[1][0].status=true;
            btnArr[1][0].btn.setText("X");
            btnArr[1][0].value=1;
            row=checkRow();
            clm=checkClm();
            putSign();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            btnArr[1][1].status=true;
            btnArr[1][1].btn.setText("X");
            btnArr[1][1].value=1;
            row=checkRow();
            clm=checkClm();
            putSign();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
            btnArr[1][2].status=true;
            btnArr[1][2].btn.setText("X");
            btnArr[1][2].value=1;
            row=checkRow();
            clm=checkClm();
            putSign();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
            btnArr[2][0].status=true;
            btnArr[2][0].btn.setText("X");
            btnArr[2][0].value=1;
            row=checkRow();
            clm=checkClm();
            putSign();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
            btnArr[2][1].status=true;
            btnArr[2][1].btn.setText("X");
            btnArr[2][1].value=1;
            row=checkRow();
            clm=checkClm();
            putSign();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
            btnArr[2][2].status=true;
            btnArr[2][2].btn.setText("X");
            btnArr[2][2].value=1;
            row=checkRow();
            clm=checkClm();
            putSign();
    }//GEN-LAST:event_jButton9ActionPerformed
    
    private void putSign()
    {
        try
        {
        if(row!=0 && rowVal>=clmVal)
            {
                if(!btnArr[row-1][row1[row-1]].status)
                {
                    btnArr[row-1][row1[row-1]].btn.setText("O");
                    btnArr[row-1][row1[row-1]].value=-1;
                    btnArr[row-1][row1[row-1]].status=true;
                }
            }
        }
        catch(Exception e)
        {
//            else
//            {
                if(!btnArr[clm1[clm-1]][clm-1].status)
                {
                    btnArr[clm1[clm-1]][clm-1].btn.setText("O");
                    btnArr[clm1[clm-1]][clm-1].value=-1;
                    btnArr[clm1[clm-1]][clm-1].status=true;
                }
//            }
        }
    }
    private int checkRow()
    {
        int tot=0,tot1=0,tot2=0,tot3=0;
        for(int i=0;i<3;i++)
        {
            tot1+=btnArr[0][i].value;
            if(!btnArr[0][i].status)
            {
                row1[0]=i;
            }
        }
        if(tot1>tot)
                tot=1;
        for(int i=1;i<3;i++)
        {
            tot2+=btnArr[1][i].value;
            if(!btnArr[1][i].status)
            {
                row1[1]=i;
            }
        }
            if(tot2>tot)
                tot=2;
        for(int i=1;i<3;i++)
        {
            tot3+=btnArr[2][i].value;
            if(!btnArr[2][i].status)
            {
                row1[2]=i;
            }
        }
        if(tot3>tot)
                tot=3;
        if(tot==1)
        {
            rowVal=tot1;           
        }
        else if(tot==2)
        {
            rowVal=tot2;
        }
        else if(tot==3)
        {
            rowVal=tot3;
        }
        else
        {
            rowVal=0;
        }
        return tot;
    }
    private int checkClm()
    {
        int tot=0,tot1=0,tot2=0,tot3=0;
        for(int i=0;i<3;i++)
        {
            tot1+=btnArr[i][0].value;
            if(!btnArr[i][0].status)
            {
                clm1[0]=i;
            }
        }
            if(tot1>tot)
                tot=1;
        for(int i=0;i<3;i++)
        {
            tot2+=btnArr[i][1].value;
            if(!btnArr[i][1].status)
            {
                clm1[0]=i;
            }
        }
            if(tot2>tot)
                tot=2;
        for(int i=0;i<3;i++)
        {
            tot3+=btnArr[i][2].value;
            if(!btnArr[i][2].status)
            {
                clm1[0]=i;
            }
        }
            if(tot3>tot)
                tot=3;
        if(tot==1)
        {
            clmVal=tot1;           
        }
        else if(tot==2)
        {
            clmVal=tot2;
        }
        else if(tot==3)
        {
            clmVal=tot3;
        }
        else
        {
            clmVal=0;
        }
        return tot;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}

class Btn
{
    JButton btn=new JButton();
    boolean status=false;
    int value=0;
}
class PlayCom
{
    String name;
    int val=1;
}