/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tictac;


import javax.swing.JButton;
import javax.swing.UIManager;

/**
 *
 * @author dell
 */
public class Board extends javax.swing.JFrame{

    /**
     * Creates new form Board
     */
    boolean player;
    Button []btnArr=new Button[9];
    public Board() {
        initComponents();
        player=true;
        for(int i=0;i<9;i++)
        {
            btnArr[i]=new Button();
        }
        btnArr[0].btn=B1;
        btnArr[1].btn=B2;
        btnArr[2].btn=B3;
        btnArr[3].btn=B4;
        btnArr[4].btn=B5;
        btnArr[5].btn=B6;
        btnArr[6].btn=B7;
        btnArr[7].btn=B8;
        btnArr[8].btn=B9;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        B1.setText("jButton1");
        B1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setText("jButton2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setText("jButton3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setText("jButton4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setText("jButton5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setText("jButton6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setText("jButton7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setText("jButton8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(51, 51, 255));
        B9.setText("jButton9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        jLabel2.setText("---");

        jButton1.setText("Pause");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(B8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B6, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(B9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(240, 240, 240)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
            .addGroup(layout.createSequentialGroup()
                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(B7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        if(btnArr[0].status==false)
        {
            btnArr[0].status=true;
            if(player)
            {
                btnArr[0].btn.setText("X");
                player=false;
                btnArr[0].value=1;
            }
            else
            {
                btnArr[0].btn.setText("O");
                player=true;
                btnArr[0].value=-1;
            }
            if((btnArr[0].value+btnArr[1].value+btnArr[2].value)==3 || (btnArr[0].value+btnArr[3].value+btnArr[6].value)==3 || (btnArr[0].value+btnArr[4].value+btnArr[8].value)==3)
            {
               jLabel2.setText("1st player won !");
            }
            if((btnArr[0].value+btnArr[1].value+btnArr[2].value)==-3 || (btnArr[0].value+btnArr[3].value+btnArr[6].value)==-3 || (btnArr[0].value+btnArr[4].value+btnArr[8].value)==-3)
            {
               jLabel2.setText("2nd player won !");
            }
            
//            if((btnArr[1].status && btnArr[2].status) || (btnArr[3].status && btnArr[6].status) || (btnArr[4].status && btnArr[8].status))
//                {
//                    if(((btnArr[1].btn.getText().equals(btnArr[2].btn.getText())) && btnArr[1].btn.getText().equals(btnArr[0].btn.getText()) )||((btnArr[3].btn.getText().equals(btnArr[6].btn.getText())) && btnArr[3].btn.getText().equals(btnArr[0].btn.getText()))|| ((btnArr[4].btn.getText().equals(btnArr[8].btn.getText())) && btnArr[4].btn.getText().equals(btnArr[0].btn.getText())) )
//                    {
//                          jLabel2.setText("You Won!");
//                    }
//                }
        }
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        
        if(btnArr[1].status==false)
        {
            btnArr[1].status=true;
            if(player)
            {
                btnArr[1].btn.setText("X");
                player=false;
                btnArr[1].value=1;
            }
            else
            {
                btnArr[1].btn.setText("O");
                player=true;
                btnArr[1].value=-1;
            }
            if((btnArr[0].value+btnArr[1].value+btnArr[2].value)==3 || (btnArr[1].value+btnArr[4].value+btnArr[7].value)==3)
            {
               jLabel2.setText("1st player won !");
            }
            if((btnArr[0].value+btnArr[1].value+btnArr[2].value)==-3 || (btnArr[1].value+btnArr[4].value+btnArr[7].value)==-3)
            {
               jLabel2.setText("2nd player won !");
            }
//            if((btnArr[0].status && btnArr[2].status) || (btnArr[4].status && btnArr[7].status))
//                {
//                    if(((btnArr[0].btn.getText()==btnArr[2].btn.getText()) && btnArr[1].btn.getText().equals(btnArr[0].btn.getText()))||((btnArr[4].btn.getText()==btnArr[7].btn.getText())&& btnArr[1].btn.getText().equals(btnArr[4].btn.getText())))
//                    {
//                        jLabel2.setText("You Won!");
//                    }
//                }
            
        }
        
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        if(btnArr[2].status==false)
        {
            btnArr[2].status=true;
            if(player)
            {
                btnArr[2].btn.setText("X");
                player=false;
                btnArr[2].value=1;
            }
            else
            {
                btnArr[2].btn.setText("O");
                player=true;
                btnArr[2].value=-1;
            }
            if((btnArr[0].value+btnArr[1].value+btnArr[2].value)==3 || (btnArr[2].value+btnArr[5].value+btnArr[8].value)==3 || (btnArr[2].value+btnArr[4].value+btnArr[6].value)==3)
            {
               jLabel2.setText("1st player won !");
            }
            if((btnArr[0].value+btnArr[1].value+btnArr[2].value)==-3 || (btnArr[2].value+btnArr[5].value+btnArr[8].value)==-3 || (btnArr[2].value+btnArr[4].value+btnArr[6].value)==-3)
            {
               jLabel2.setText("2nd player won !");
            }
//            if((btnArr[0].status && btnArr[1].status) || (btnArr[5].status && btnArr[8].status) || (btnArr[4].status && btnArr[6].status))
//                {
//                    if(((btnArr[0].btn.getText().equals(btnArr[1].btn.getText()))&& btnArr[2].btn.getText().equals(btnArr[0].btn.getText()))||((btnArr[5].btn.getText().equals(btnArr[8].btn.getText())) && btnArr[2].btn.getText().equals(btnArr[5].btn.getText())) || ((btnArr[4].btn.getText().equals(btnArr[6].btn.getText()))&& btnArr[2].btn.getText().equals(btnArr[4].btn.getText())))
//                    {
//                       jLabel2.setText("You Won!");
//                    }
//                }
            
        }
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed

         if(btnArr[3].status==false)
         {
            btnArr[3].status=true;
            if(player)
            {
                btnArr[3].btn.setText("X");
                player=false;
                btnArr[3].value=1;
            }
            else
            {
                btnArr[3].btn.setText("O");
                player=true;
                btnArr[3].value=-1;
            }
            
            if((btnArr[0].status && btnArr[6].status) || (btnArr[4].status && btnArr[5].status) )
            {
                if((btnArr[0].btn.getText()==btnArr[6].btn.getText())||(btnArr[4].btn.getText()==btnArr[5].btn.getText()))
                {
                    if(btnArr[3].btn.getText().equals(btnArr[0].btn.getText()) || btnArr[3].btn.getText().equals(btnArr[4].btn.getText()))
                        {
                           jLabel2.setText("You Won!");
                        }
                }
            }

        }
        
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        
        if(btnArr[4].status==false)
         {
            btnArr[4].status=true;
            if(player)
            {
                btnArr[4].btn.setText("X");
                player=false;
                btnArr[4].value=1;
            }
            else
            {
                btnArr[4].btn.setText("O");
                player=true;
                btnArr[4].value=-1;
            }
            
            if((btnArr[3].status && btnArr[5].status) || (btnArr[1].status && btnArr[7].status) || (btnArr[0].status && btnArr[8].status) || (btnArr[2].status && btnArr[6].status))
                {
                    if((btnArr[3].btn.getText()==btnArr[5].btn.getText())||(btnArr[1].btn.getText()==btnArr[7].btn.getText()) || (btnArr[0].btn.getText()==btnArr[8].btn.getText()) || (btnArr[2].btn.getText()==btnArr[6].btn.getText()))
                    {
                        if(btnArr[4].btn.getText().equals(btnArr[3].btn.getText()) || btnArr[4].btn.getText().equals(btnArr[1].btn.getText()) || btnArr[4].btn.getText().equals(btnArr[8].btn.getText()) || btnArr[4].btn.getText().equals(btnArr[6].btn.getText()))
                        {
                            jLabel2.setText("You Won!");
                        }
                    }
                }
            
        }
        
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
       
        if(btnArr[5].status==false)
         {
            btnArr[5].status=true;
            if(player)
            {
                btnArr[5].btn.setText("X");
                player=false;
                btnArr[5].value=1;
            }
            else
            {
                btnArr[5].btn.setText("O");
                player=true;
                btnArr[5].value=-1;
            }
            
            if(((btnArr[2].status && btnArr[8].status)) && (btnArr[2].btn.getText()==btnArr[8].btn.getText()) || ((btnArr[3].status && btnArr[4].status) && (btnArr[3].btn.getText()==btnArr[4].btn.getText())) )
                {
                        if(btnArr[5].btn.getText().equals(btnArr[2].btn.getText()) || btnArr[5].btn.getText().equals(btnArr[3].btn.getText()))
                        {
                            jLabel2.setText("You Won!");
                        }
                }
            
        }
        
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed

         if(btnArr[6].status==false)
         {
            btnArr[6].status=true;
            if(player)
            {
                btnArr[6].btn.setText("X");
                player=false;
                btnArr[6].value=1;
            }
            else
            {
                btnArr[6].btn.setText("O");
                player=true;
                btnArr[6].value=-1;
            }
            
            if((btnArr[0].status && btnArr[3].status) || (btnArr[7].status && btnArr[8].status) || (btnArr[2].status && btnArr[4].status) )
                {
                    if(((btnArr[0].btn.getText()==btnArr[3].btn.getText()) && btnArr[6].btn.getText().equals(btnArr[0].btn.getText()))||((btnArr[7].btn.getText()==btnArr[8].btn.getText()) && btnArr[6].btn.getText().equals(btnArr[7].btn.getText())) || ((btnArr[2].btn.getText()==btnArr[4].btn.getText()) && btnArr[6].btn.getText().equals(btnArr[4].btn.getText())))
                    {
                        jLabel2.setText("You Won!");
                    }
                }
        }
        
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        
         if(btnArr[7].status==false)
         {
            btnArr[7].status=true;
            if(player)
            {
                btnArr[7].btn.setText("X");
                player=false;
                btnArr[7].value=1;
            }
            else
            {
                btnArr[7].btn.setText("O");
                player=true;
                btnArr[7].value=-1;
            }

            if((btnArr[1].status && btnArr[4].status) || (btnArr[6].status && btnArr[8].status) )
                {
                    if(((btnArr[1].btn.getText()==btnArr[4].btn.getText()) && btnArr[7].btn.getText().equals(btnArr[1].btn.getText()) )||((btnArr[6].btn.getText()==btnArr[8].btn.getText())&&  btnArr[7].btn.getText().equals(btnArr[6].btn.getText())))
                    {
                        jLabel2.setText("You Won!");
                    }
                }
            
        }
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed

         if(btnArr[8].status==false)
         {
            btnArr[8].status=true;
            if(player)
            {
                btnArr[8].btn.setText("X");
                player=false;
                btnArr[8].value=1;
            }
            else
            {
                btnArr[8].btn.setText("O");
                player=true;
                btnArr[8].value=-1;
            }
            
            if((btnArr[2].status && btnArr[5].status) || (btnArr[7].status && btnArr[6].status) || (btnArr[0].status && btnArr[4].status) )
                {
                    if(((btnArr[2].btn.getText()==btnArr[5].btn.getText()) && btnArr[8].btn.getText().equals(btnArr[2].btn.getText()))||((btnArr[7].btn.getText()==btnArr[6].btn.getText()) && btnArr[8].btn.getText().equals(btnArr[7].btn.getText())) || ((btnArr[0].btn.getText()==btnArr[4].btn.getText()) && btnArr[8].btn.getText().equals(btnArr[4].btn.getText())))
                    {
                        jLabel2.setText("You Won!");
                    }
                }
            
        }
        
    }//GEN-LAST:event_B9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
class Button
{
    JButton btn=new JButton();
    boolean status=false;
    int value=0;
}